# Generated by Django 5.0.2 on 2024-03-13 13:32

import django.db.models.deletion
import martor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.CharField(max_length=400, verbose_name='描述/导语/编者按')),
                ('content', martor.models.MartorField()),
                ('pub_date', models.DateTimeField(verbose_name='上传时间')),
            ],
        ),
        migrations.CreateModel(
            name='Categoty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='名称')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='名称')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='文件')),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.categoty'),
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='名称')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.categoty')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='col',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.column'),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('number', models.IntegerField(verbose_name='期次')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.categoty')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.issue'),
        ),
    ]
