# Generated by Django 5.0.2 on 2024-03-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_alter_article_options_alter_categoty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='attachment',
            field=models.JSONField(default={}, verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(default='', max_length=400, verbose_name='描述/导语/编者按'),
        ),
    ]
