# Generated by Django 5.0.2 on 2024-03-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_article_attachment_alter_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='attachment',
            field=models.JSONField(blank=True, default={}, verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='描述/导语/编者按'),
        ),
    ]
