# Generated by Django 5.0.2 on 2024-03-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_attach_remove_article_attachment_article_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attach',
            options={'verbose_name': '附件', 'verbose_name_plural': '附件'},
        ),
        migrations.AlterField(
            model_name='article',
            name='attachment',
            field=models.ManyToManyField(to='docs.attach', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='描述/导语/编者按'),
        ),
        migrations.AlterField(
            model_name='categoty',
            name='description',
            field=models.TextField(max_length=200, verbose_name='描述'),
        ),
    ]
