# Generated by Django 5.0.2 on 2024-03-13 15:39

import martor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_alter_article_attachment_alter_attach_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='key',
            field=martor.models.MartorField(blank=True),
        ),
    ]
