# Generated by Django 4.2.10 on 2024-03-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_article_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='', max_length=200, verbose_name='作者'),
            preserve_default=False,
        ),
    ]
