# Generated by Django 4.2.10 on 2024-03-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_alter_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, max_length=200, verbose_name='作者'),
        ),
    ]
